[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.makers.acebook:acebook:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------< com.makers.acebook:acebook >---------------------
[INFO] Building acebook 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ acebook >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ acebook <<<
[INFO] 
Downloading from central: https://repo.maven.apache.org/maven2/com/sparkjava/spark-core/maven-metadata.xml
Progress (1): 971 B                   Downloaded from central: https://repo.maven.apache.org/maven2/com/sparkjava/spark-core/maven-metadata.xml (971 B at 1.5 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/junit/junit/maven-metadata.xml
Progress (1): 1.2 kB                    Downloaded from central: https://repo.maven.apache.org/maven2/junit/junit/maven-metadata.xml (1.2 kB at 82 kB/s)
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ acebook ---
acebook-test
0    [Main.main()] INFO  org.flywaydb.core.internal.license.VersionPrinter  - Flyway Community Edition 6.0.1 by Boxfuse
[WARNING] 
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:830)
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:postgresql://localhost:5432/acebook-test) for user 'null': FATAL: database "acebook-test" does not exist
--------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 3D000
Error Code : 0
Message    : FATAL: database "acebook-test" does not exist

    at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection (JdbcUtils.java:60)
    at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init> (JdbcConnectionFactory.java:80)
    at org.flywaydb.core.Flyway.execute (Flyway.java:431)
    at org.flywaydb.core.Flyway.migrate (Flyway.java:142)
    at Main.main (Main.java:24)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:830)
Caused by: org.postgresql.util.PSQLException: FATAL: database "acebook-test" does not exist
    at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages (ConnectionFactoryImpl.java:684)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl (ConnectionFactoryImpl.java:199)
    at org.postgresql.core.ConnectionFactory.openConnection (ConnectionFactory.java:66)
    at org.postgresql.jdbc2.AbstractJdbc2Connection.<init> (AbstractJdbc2Connection.java:127)
    at org.postgresql.jdbc3.AbstractJdbc3Connection.<init> (AbstractJdbc3Connection.java:29)
    at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init> (AbstractJdbc3gConnection.java:21)
    at org.postgresql.jdbc4.AbstractJdbc4Connection.<init> (AbstractJdbc4Connection.java:41)
    at org.postgresql.jdbc4.Jdbc4Connection.<init> (Jdbc4Connection.java:24)
    at org.postgresql.Driver.makeConnection (Driver.java:414)
    at org.postgresql.Driver.connect (Driver.java:282)
    at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver (DriverDataSource.java:447)
    at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection (DriverDataSource.java:413)
    at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection (JdbcUtils.java:56)
    at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init> (JdbcConnectionFactory.java:80)
    at org.flywaydb.core.Flyway.execute (Flyway.java:431)
    at org.flywaydb.core.Flyway.migrate (Flyway.java:142)
    at Main.main (Main.java:24)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:830)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.241 s
[INFO] Finished at: 2020-02-05T11:03:33Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project acebook: An exception occured while executing the Java class. null: InvocationTargetException: 
[ERROR] Unable to obtain connection from database (jdbc:postgresql://localhost:5432/acebook-test) for user 'null': FATAL: database "acebook-test" does not exist
[ERROR] --------------------------------------------------------------------------------------------------------------------------------------------------------
[ERROR] SQL State  : 3D000
[ERROR] Error Code : 0
[ERROR] Message    : FATAL: database "acebook-test" does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
